apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: "default_project"
  tags:
    - scorecardstattest
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ajinkya-harness/hello-world-app
spec:
  type: service
  owner: "IDPAdmin"
  lifecycle: experimental
